name: My First Github Action
on: [push]
jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello world!!"
            - run: echo "this is step number 2"
            - uses: actions/checkout@v2
            - run: tree
            - uses: actions/setup-node@v2
              with:
                node-version: '14.7.0'
            - name: install node_modules
              run: yarn
            - name: Build the project
              run: yarn build
            - name: setup finish
              run: echo "you did it!"

